ALTER TABLE notes ADD COLUMN task_id INTEGER REFERENCES tasks(id) ON DELETE CASCADE;
ALTER TABLE notes ADD COLUMN file_id INTEGER REFERENCES files(id) ON DELETE CASCADE;

CREATE TABLE note_versions (
    id SERIAL PRIMARY KEY,
    note_id INTEGER NOT NULL,
    content_markdown TEXT NOT NULL,
    author_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL
);
